config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :tournaments, only: [:index, :show, :new, :create] do
    resources :games, only: :create
  end
end

app/views/pages/home.html.erb
<div class="container d-flex justify-content-center">
  <div class="subcontainer">
    <div class="d-flex justify-content-center mb-4">
      <%= image_tag 'logo.png', width: '250', height: '250' %>
    </div>

    <p class="text-center"><strong>Ceci est une version bêta pour les copains.</strong></p>

    <div class="d-flex justify-content-center mb-4">
      <%= link_to 'Les Tournois', tournaments_path, class: 'btn btn-primary mr-3' %>
      <%= link_to 'Créer un Tournoi', new_tournament_path, class: 'btn btn-primary' %>
    </div>

    <p class="">Le confinement a entraîné une recrudescence des tournois de poker entre potes.</p>

    <p class="brand-color"><strong>Cette app est destinée aux joueurs de Winamax qui veulent suivre l'évolution des performances de chacun dans leurs tournois privés.</strong></p>

    <p class="">Le principe est le suivant :</p>
    <ul class="">
      <li class="">Tu crées un compte.</li>
      <li class="">Tu crées un tournoi.</li>
      <li class="">Après chaque petite partie entre potes tu viens renseigner le code Winamax <em>(dans ton profil tu peux retrouver les tournois auxquels tu as participé)</em>.</li>
      <li class="">Les stats de chaque joueur se calculent automatiquement.</li>
    </ul>

    <p class="">Évolutions possibles :</p>
    <ul class="">
      <li class="">Ajout de badges pour récompenser les meilleurs et souiller les pires.</li>
      <li class="">Une page par joueur pour avoir ses stats au fil des parties à la <%= link_to 'Sharkscope', 'https://fr.sharkscope.com/' %>.</li>
    </ul>

    <p class="">Pour le moment les tournois sont visibles par tout le monde.</p>
    <div class="d-flex justify-content-center mb-4">
      <%= link_to 'Les Tournois', tournaments_path, class: 'btn btn-primary mr-3' %>
      <%= link_to 'Créer un Tournoi', new_tournament_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>